import type { BadgeKey } from "./badges";

/**
 * What each badge is for, and what its title is referring to. The prose the
 * badge modal draws, and the answer to the user's own question: "a picture of
 * the medal, and what this badge means".
 *
 * **A peer of `badges.ts`, not a wrapper, and it is here rather than there for a
 * measured reason.** `reveal.ts` carries the note that `BADGE_CATALOG` "is a
 * pure array of strings and comes along harmlessly"; it is imported by
 * `reward-toast.tsx`, which `/today` mounts unconditionally. So anything added
 * to `badges.ts` ships to every visit of a screen that will never render it.
 * Fourteen conditions and fourteen glosses are ~4.6 kB raw — small, and
 * entirely wasted there. This module is imported by `badge-dialog.tsx` and
 * `scripts/check-gamification.ts` and by nothing else. In particular
 * `reveal.ts`, `on-card-created.ts` and `recompute.ts` must not import it.
 *
 * Browser-safe by construction: no `import "server-only"`, no zod value import,
 * no React, no clock, no database. The `BadgeKey` import is **type-only**, so it
 * adds no runtime edge and cannot create a cycle.
 *
 * **No art path here.** `BADGE_ART` in `badge-art.ts` owns that, is generated by
 * `tools/make_badge_assets.py`, and carries content-hashed filenames — a
 * hand-written path in this file would drift from the files on disk the first
 * time a badge was regenerated. F11–F18 brief [C3].
 *
 * **Register**, enforced by `npm run stats:check` rather than remembered:
 *
 *  - No second person. The app uses "you" only about its own machinery
 *    ("Pronunciation and meaning are fetched for you"), never to congratulate.
 *    Stating the rule as a fact about cards is also what lets one string serve
 *    both the earned and the unearned state, which F13 D2 requires.
 *  - No exclamation, no flattery, no loss aversion, no deadline.
 *  - Typographic apostrophes only, per the note at the top of `levels.ts`.
 *  - `condition` ≤ 140 characters, `gloss` ≤ 320.
 */

export type BadgeMeta = {
  /** The rule. One sentence, present tense, impersonal. */
  condition: string;
  /** What the title refers to, and why the day is the day. One to three sentences. */
  gloss: string;
};

/**
 * A total `Record`, deliberately, not a `Partial`. A fifteenth badge added to
 * `BADGE_CATALOG` with no metadata is a `npm run typecheck` error in the same
 * session, which is a stronger guard than the check script and arrives sooner.
 * The same discipline `BADGE_ART` uses, for the same reason.
 */
export const BADGE_META: Record<BadgeKey, BadgeMeta> = {
  first_card: {
    condition: "The first card ever made.",
    gloss:
      "The trick was never knowing the words. It was having six of them in a pocket at the moment somebody asked.",
  },
  full_week: {
    condition:
      "Seven cards on seven consecutive days. Awarded again at fourteen, twenty-one, and every seventh day after that.",
    gloss:
      "A ration is a week’s worth, issued once and not topped up. A missed day takes nothing back; it restarts the count.",
  },
  sunday: {
    condition: "A card made on a Sunday.",
    gloss:
      "Ration books were stamped by the week, and the week ended on a Sunday whether or not anyone felt like queuing.",
  },
  midnight_oil: {
    condition:
      "A card made between midnight and 03:59 local time. Four o’clock is morning.",
    gloss:
      "The oil in the phrase was real, and burning it was a complaint rather than a boast. The hour is read from the clock where the card was made, not from the server’s.",
  },
  new_year: {
    condition: "A card made on 1 January.",
    gloss: "Most resolutions are announced. This one has a timestamp.",
  },
  womens_day: {
    condition: "A card made on 8 March, International Women’s Day.",
    gloss:
      "Marked since 1911, before most of the people it was marked for could vote. The card is the observance.",
  },
  world_book_day: {
    condition: "A card made on 23 April, World Book and Copyright Day.",
    gloss:
      "UNESCO took the date from Cervantes, buried on 23 April 1616, and from Shakespeare, recorded dead on the same date — England was still keeping the Julian calendar, so the two lie ten days apart. A small lesson in how records work.",
  },
  fathers_day: {
    condition: "A card made on the third Sunday of June.",
    gloss:
      "Always a Sunday, so it always arrives with the Sunday badge attached.",
  },
  indonesia_independence: {
    condition: "A card made on 17 August, Indonesian Independence Day.",
    gloss:
      "Read out on a Friday morning in 1945, from a text drafted overnight in a borrowed house. A day for speeches, and this is a shop that sells the words for them.",
  },
  ibu: {
    condition: "A card made on 22 December, Hari Ibu.",
    gloss:
      "Indonesian Mother’s Day, dated to the first Indonesian Women’s Congress in 1928 rather than to a greetings-card season.",
  },
  christmas: {
    condition: "A card made on 25 December.",
    gloss:
      "Dickens sent three ghosts and each of them had a speech. This one shows six words and leaves.",
  },
  year_end: {
    condition: "A card made on 31 December.",
    gloss:
      "The final entry before the book is closed. Whatever the sixth word turned out to be, it stands.",
  },
  leap_day: {
    condition: "A card made on 29 February.",
    gloss:
      "Available on about one day in fifteen hundred, once the skipped centuries are counted. The rarest thing on this shelf, and nothing about it is difficult.",
  },
  tolkien: {
    condition: "A card made on 2 September, the day J.R.R. Tolkien died.",
    gloss:
      "Tolkien died on 2 September 1973, a Sunday, at eighty-one. He was a philologist first and a novelist second: the languages came before the story, and the story was built to give them somewhere to be spoken. Somebody in Mordor presumably marked the date.",
  },
  three_in_a_week: {
    condition:
      "Three cards inside one week, counted Monday to Sunday. Awarded on the third card of a week, once per week.",
    gloss:
      "Three is where a week stops looking accidental. It is not the full ration and was never meant to be — the office that issued these took three stamps as evidence that somebody had been in, and did not ask what happened on the other four days.",
  },
  thirty_day_streak: {
    condition:
      "Thirty cards on thirty consecutive days. Awarded again at sixty, at ninety, and every thirtieth day after that.",
    gloss:
      "The line belongs to a covered order who repeat it whenever somebody does the plainly correct thing, which is most of what a creed is for. Thirty days is about where a habit stops needing to be argued with. A missed day restarts the count and takes nothing away.",
  },
  dumbledore: {
    condition: "A card made on 30 June, the day Albus Dumbledore died.",
    gloss:
      "Killed on the Astronomy Tower shortly after midnight on 30 June 1997, by two words, spoken by the man he had asked to speak them. The date is fixed by arithmetic rather than by a calendar: the bequests arrived on 31 July, thirty-one days later.",
  },
  dobby: {
    condition: "A card made on 30 March, the day Dobby died.",
    gloss:
      "Dobby died at Shell Cottage on 30 March 1998 and was buried the next morning under a stone cut by hand, six words long. The books never give the date; it is reconstructed from the Easter chronology, which makes it the one day on this shelf that readers worked out rather than read.",
  },
  five_shares: {
    condition:
      "Five words handed to somebody else. Awarded again at ten, at fifteen, and every fifth word shared after that.",
    gloss:
      "The parable is about the one traveller who stopped, and none of it is about vocabulary. The mechanism is the same either way: a word costs nothing to pass on and is worth nothing until somebody does.",
  },
  ten_journal_lines: {
    condition:
      "Ten lines written in the journal. Awarded again at twenty, at thirty, and every tenth line after that.",
    gloss:
      "A maester forges one link for each subject he masters and wears the whole chain for the rest of his life. The links are different metals and are not meant to match. Ten lines is one link, and the chain is only ever added to.",
  },
};

/**
 * Null for a key that is not in the catalog, mirroring `badgeTitle` exactly. The
 * two must behave the same way or the next reader will assume they do and be
 * wrong. The shelf already drops unknown keys upstream in `getProfileStats`, so
 * this is belt and braces.
 */
export function badgeMeta(key: string): BadgeMeta | null {
  return (BADGE_META as Record<string, BadgeMeta>)[key] ?? null;
}
